export const FEATURE_FLAG_NAME = 'referralSalesAgentAttribution';

export const ATTRIBUTION_SOURCE = Object.freeze({
  MANUAL_ASSIGN: 'manual_assign',
  MANUAL_CHANGE: 'manual_change',
  MANUAL_REVOKE: 'manual_revoke',
});

export const ACTIVITY_LOG_ACTION = Object.freeze({
  ASSIGNED: 'REFERRAL_SALES_AGENT_ASSIGNED',
  CHANGED: 'REFERRAL_SALES_AGENT_CHANGED',
  REVOKED: 'REFERRAL_SALES_AGENT_REVOKED',
  ATTRIBUTION_JOB_PINNED: 'EMPLOYEE_ATTRIBUTION_JOB_PINNED',
  ATTRIBUTION_JOB_UNPINNED: 'EMPLOYEE_ATTRIBUTION_JOB_UNPINNED',
  MANUAL_BACKFILLED: 'REFERRAL_MANUAL_BACKFILLED',
});

export const ERROR_CODE = Object.freeze({
  CANDIDATE_LEVEL_FROZEN: 'CANDIDATE_LEVEL_FROZEN',
  CROSS_TENANT_ASSIGNMENT_FORBIDDEN: 'CROSS_TENANT_ASSIGNMENT_FORBIDDEN',
  CONCURRENT_ASSIGNMENT_RACE: 'CONCURRENT_ASSIGNMENT_RACE',
  STALE_PRECONDITION: 'STALE_PRECONDITION',
  SALES_AGENT_ROLE_REQUIRED: 'SALES_AGENT_ROLE_REQUIRED',
  ASSIGN_DATE_IN_FUTURE: 'ASSIGN_DATE_IN_FUTURE',
  ALREADY_REFERRED: 'ALREADY_REFERRED',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  REFERRER_NOT_FOUND: 'REFERRER_NOT_FOUND',
  REFERRER_SELF_REFERENCE: 'REFERRER_SELF_REFERENCE',
});

export const DRIFT_THRESHOLD = Object.freeze({
  WARN: 10,
  PAGE: 50,
});
