// Module and area labels of the Settings → Roles permission matrix. The backend has no copy of this
// catalog; it mirrors frontend shared/lib/roles-permissions.ts PERMISSION_SECTIONS — keep the two in sync.
// Raw role permissions are "<module>.<area>:<actions>" (e.g. "ats.jobs:view,create").
export const PERMISSION_MODULES = Object.freeze([
  { id: 'general', label: 'General', areas: { dashboard: 'Dashboard' } },
  {
    id: 'settings',
    label: 'Settings',
    areas: {
      roles: 'User Roles',
      users: 'Users',
      'personal-information': 'Personal Information',
      'interview-availability': 'Interview Availability',
      attendance: 'Attendance',
      agents: 'Agents',
      'company-email': 'Company work email',
      'company-number': 'Company work number',
      'candidate-sop': 'Employee SOP',
      'email-templates': 'My email templates',
      'job-templates': 'My jobs template',
      'email-templates-admin': "All agents' email templates (admin)",
      'users.impersonate': 'Impersonate users (Login as)',
    },
  },
  { id: 'candidate', label: 'Employee', areas: { courses: 'Courses' } },
  {
    id: 'ats',
    label: 'ATS',
    areas: {
      'my-profile': 'My Profile',
      jobs: 'Jobs',
      candidates: 'Candidates',
      referralLeads: 'Referral leads',
      'share-candidate-form': 'Share candidate form',
      recruiters: 'Recruiters',
      interviews: 'Interviews',
      offers: 'Offers',
      'pre-boarding': 'Pre-boarding',
      'payroll-details': 'Payroll & bank details',
      onboarding: 'Onboarding',
      employees: 'Employees',
      'employees.transfer': 'Transfer employee (internal mobility)',
      analytics: 'Analytics',
      'external-jobs': 'External jobs',
    },
  },
  {
    id: 'organization',
    label: 'Organization',
    areas: { chart: 'Org Chart', structure: 'Structure', departments: 'Departments', directory: 'Directory', scenarios: 'Scenarios' },
  },
  {
    id: 'communication',
    label: 'Communication',
    areas: {
      emails: 'Emails',
      chats: 'Chats',
      calling: 'Calling',
      'call-recording': 'Call Recording',
      'call-transcripts': 'Call Transcripts',
      'call-ai': 'Call AI Features',
      meetings: 'Meetings & Recordings',
      'files-storage': 'Files Storage',
    },
  },
  {
    id: 'training',
    label: 'Training Management',
    areas: {
      categories: 'Categories',
      positions: 'Positions',
      modules: 'Modules',
      assessments: 'Assessments',
      attendance: 'Attendance Tracking',
      mentors: 'Mentors',
      students: 'Students',
      evaluation: 'Evaluation',
      analytics: 'Analytics',
    },
  },
  {
    id: 'project',
    label: 'Project Management',
    areas: {
      projects: 'Projects',
      'my-projects': 'My Projects',
      tasks: 'My Tasks',
      kanban: 'Task Board (Kanban)',
      teams: 'Teams',
      analytics: 'Analytics',
    },
  },
  { id: 'logs', label: 'Logs', areas: { activity: 'Logs Activity' } },
  { id: 'support', label: 'Support', areas: { 'help-and-support': 'Help & Support', tickets: 'Support Tickets' } },
  { id: 'ai', label: 'AI', areas: { chatbot: 'Chatbot Access' } },
]);
